export const REDUX_WEBSOCKET_RECONNECT_ATTEMPT = 'REDUX_WEBSOCKET::RECONNECT_ATTEMPT'
export const REDUX_WEBSOCKET_BEGIN_RECONNECT = 'REDUX_WEBSOCKET::BEGIN_RECONNECT'
export const REDUX_WEBSOCKET_RECONNECTED = 'REDUX_WEBSOCKET::RECONNECTED'
export const REDUX_WEBSOCKET_CONNECT = 'REDUX_WEBSOCKET::CONNECT'
export const REDUX_WEBSOCKET_DISCONNECT = 'REDUX_WEBSOCKET::DISCONNECT'
export const REDUX_WEBSOCKET_OPEN = 'REDUX_WEBSOCKET::OPEN'
export const REDUX_WEBSOCKET_CLOSED = 'REDUX_WEBSOCKET::CLOSED'
export const REDUX_WEBSOCKET_MESSAGE = 'REDUX_WEBSOCKET::MESSAGE'
export const REDUX_WEBSOCKET_SEND = 'REDUX_WEBSOCKET::SEND'
export const REDUX_WEBSOCKET_ERROR = 'REDUX_WEBSOCKET::ERROR'

export const REDUX_WEBSOCKET_ESTADO = 'REDUX_WEBSOCKET_ESTADO'
export const REDUX_MSG_SALIENTE = 'REDUX_MSG_SALIENTE'
export const REDUX_MSG_ENTRANTE = 'REDUX_MSG_ENTRANTE'
export const REDUX_FLAG_ESTADO = 'REDUX_FLAG_ESTADO'
export const REDUX_FLAG_TITULO = 'REDUX_FLAG_TITULO'
export const REDUX_FLAG_MENSAJE = 'REDUX_FLAG_MENSAJE'

export const REDUX_USUARIO_DATOS_PERSONALES = 'REDUX_USUARIO_DATOS_PERSONALES'
export const REDUX_USUARIO_OPERACION = 'REDUX_USUARIO_OPERACION'
export const REDUX_USUARIO_SUPERVISION = 'REDUX_USUARIO_SUPERVISION'
export const REDUX_USUARIO_ADMINISTRACION = 'REDUX_USUARIO_ADMINISTRACION'

export const REDUX_USUARIO_ESTADOS = 'REDUX_USUARIO_ESTADOS'
export const REDUX_OPERADOR_ESTADO_GENERAL = 'REDUX_OPERADOR_ESTADO_GENERAL'
export const REDUX_OPERADOR_ESTADO_EXTENSION = 'REDUX_OPERADOR_ESTADO_EXTENSION'
export const REDUX_OPERADOR_ESTADO_CHAT_GENERAL = 'REDUX_OPERADOR_ESTADO_CHAT_GENERAL'

export const REDUX_USUARIO_MENU_COLA_PROPIEDADES = 'REDUX_USUARIO_MENU_COLA_PROPIEDADES'

export const REDUX_MENU_COLAS = 'REDUX_MENU_COLAS'
export const REDUX_MENU_ESTADOS = 'REDUX_MENU_ESTADOS'
export const REDUX_MENU_ESTADOS_GRUPOS = 'REDUX_MENU_ESTADOS_GRUPOS'
export const REDUX_MENU_HABILIDADES = 'REDUX_MENU_HABILIDADES'
export const REDUX_MENU_HABILIDADES_GRUPOS = 'REDUX_MENU_HABILIDADES_GRUPOS'

export const REDUX_MENU_PERMISOS = 'REDUX_MENU_PERMISOS'
export const REDUX_MENU_SECTORES = 'REDUX_MENU_SECTORES'
export const REDUX_MENU_SECTORES_HABILIDADES = 'REDUX_MENU_SECTORES_HABILIDADES'
export const REDUX_MENU_SECTORES_ESTADOS = 'REDUX_MENU_SECTORES_ESTADOS'

export const REDUX_MENU_USUARIOS = 'REDUX_MENU_USUARIOS'

export const REDUX_MENU_PERMISOS_USUARIO = 'REDUX_MENU_PERMISOS_USUARIO'
export const REDUX_MENU_HABILIDADES_USUARIO = 'REDUX_MENU_HABILIDADES_USUARIO'
export const REDUX_MENU_ESTADOS_USUARIO= 'REDUX_MENU_ESTADOS_USUARIO'

export const REALTIME_USUARIOS= 'REALTIME_USUARIOS'
